### ISSUE TITLE
[Feature Request] Material You colors 

### ISSUE THREAD

**Issue by KakarottoCake** [jarnedemeulemeester/findroid#133]
I don't think it should be hard to implement, considering that the app already uses Material 3 (Material You) design. 
Material you colors would make the app look nicer for sure.

**Comment by jarnedemeulemeester** [comment]
Material You colors was planned to come with the Material 3 redesign. 
The reason it didn't make it is because there is a conflict (bug) between the androidx.core-splashscreen library and the Material You colors. When the splash screen ends it sets the theme of the app again which removes the Material You colors.
When this is fixed I'll be sure to enable the Material You colors. :smile:

**Comment by KakarottoCake** [comment]
Sounds great! Thanks for the transparency!
