### ISSUE TITLE
Can't select external subtitles on downloaded media

### ISSUE THREAD

**Issue by OctoNezd** [jarnedemeulemeester/findroid#137]
**Describe the bug**
Can't select external subtitles (that are registered in jellyfin) on downloaded media.

Nothing happens when subtitle icon gets clicked.

**To Reproduce**
1. Download episode/movie with external subtitles
2. Play it
3. Click on subtitle icon

**Expected behavior**
Subtitle list pops up, with external subs

**Device info (please complete the following information):**
 - Device: Poco X3 NFC
 - Android version: 12
 - App version: 0.5.0

**Comment by AnonymousWebHacker** [comment]
You try again on v0.6.1 ?  https://github.com/jarnedemeulemeester/findroid/releases/tag/v0.6.1

I think that error is already fixed.

**Comment by diogotcorreia** [comment]
Hi!
I'm willing to work on this. I've already looked at the code and it doesn't seem *that* complicated. It will for sure require some changes to support downloading more than one file per video, but nothing that can be done.

I'm thinking about how to implement this and would like some comments, mainly on the following aspects:
- Should we download all available subtitles for a given video or prompt the user for the which subtitles they want?
- Would downloading intro-skipper data be useful as well?
- Would selecting download video quality be a nice addition to this? Or should it be left for a future PR?
- I'm thinking about adding toggles on the settings (e.g. downloading subtitles; downloading intro-skipper data, etc).
- We would need a better UI for managing the downloads (e.g. see which subtitles are downloaded, override defaults when downloading, etc)

Discussion would be appreciated. I'd hope to have this done in a few weeks :)

**Comment by Jcuhfehl** [comment]
That would be great, the biggest concern I have is that Jarne mentioned in the discord that he wanted to rework the downloads code, but ofc I don't know his timeline for that and whether it would be better to wait for that. As for the other questions:
> Should we download all available subtitles for a given video or prompt the user for the which subtitles they want?

I think just downloading all subtitles would be best, since they're quite small anyways, and asking the user every time might become pretty bothersome.
> Would downloading intro-skipper data be useful as well?

Seems like a good idea! Though this might be easier to implement after the rework.
> Would selecting download video quality be a nice addition to this? Or should it be left for a future PR?

This would be pretty nice. I looked into it for a bit and it seems jellyfin gives the client an HLS file which could be more complicated to download, but I can't test this because my server is too slow to transcode.
> I'm thinking about adding toggles on the settings (e.g. downloading subtitles; downloading intro-skipper data, etc).

I can't really imagine a reason a user would not want all the subtitles and the intro skipper data (if they've enabled the plugin, of course) so I don't think it is neccesary.
> We would need a better UI for managing the downloads (e.g. see which subtitles are downloaded, override defaults when downloading, etc)

Agreed, we need a better one anyways, also to see currently downloading items, bulk retry etc. This might also be better implemented after the rewrite, and is big enough it probably needs its own PR.

**Comment by diogotcorreia** [comment]
Awesome, thanks for the comments. I hadn't noticed there was a Discord server, I'll join it now!
