### ISSUE TITLE
Adapt My media

### ISSUE THREAD

**Issue by Gottarocket** [jarnedemeulemeester/findroid#156]
**Describe the feature**
Adapt My media to match the screen

**To Reproduce**
1. Go to Findroid
2. Click on My media
3. See all your media folders
4. If its 2 folders it appears too small

**Expected behavior**
Should show up as a large list if media folders are less. I have 2 folders shows and movies but they appear too small instead of adapting to mobile screen 

**Screenshots**
![](https://pictshare.net/crjihz.jpg)
**Device info (please complete the following information):**
 - Android version: 11
 - App version: Latest

**Comment by jarnedemeulemeester** [comment]
In the original design there was 1 library per row instead of 2. I changed this to 2 libraries per row because people complained that they were too big. 
I do understand that if you only have 2 libraries they should be bigger. But to make it adapt to the number of libraries would require a lot of work.
The current design is the best I can do for now.
