### ISSUE TITLE
Internal mpv-android player does not play HEVC 10 bit on Findroid

### ISSUE THREAD

**Issue by AnonymousWebHacker** [jarnedemeulemeester/findroid#176]
I have problems, with some HEVC videos.

NO WORK
```
Codec: HEVC
Profile: Main 10
Level: 93
Resolution: 1280x640
Aspect ratio: 2:1
Interlaced: No
Framerate: 23.976025
Bitrate: 886 kbps
Bit depth: 10 bit
Video range: SDR
Video range type: SDR
Color space: bt709
Color transfer: bt709
Color primaries: bt709
Pixel format: yuv420p10le
Ref frames: 1
```
WORKING
```
Codec: HEVC
Profile: Main
Level: 93
Resolution: 1280x720
Aspect ratio: 16:9
Interlaced: No
Framerate: 23.976025
Bitrate: 736 kbps
Bit depth: 8 bit
Video range: SDR
Video range type: SDR
Color space: bt709
Color transfer: bt709
Color primaries: bt709
Pixel format: yuv420p
Ref frames: 1
```

The difference is in [Pixel format: yuv420p10le]  or may be [Bit depth: 10 bit].

I tried with another external player (MX Player) and it plays the video without problems, to which I came to the conclusion that findroid, does it need the codec for that [Pixel format: yuv420p10le], right?

**Comment by AnonymousWebHacker** [comment]
Related to https://github.com/jarnedemeulemeester/findroid/issues/28

interest repos
https://github.com/vinodnimbalkar/mxplayer
https://github.com/google/ExoPlayer
https://github.com/entr0pia/FFmpeg-MX

**Comment by AnonymousWebHacker** [comment]
Situation:

There are several devices, which support transcoding at the hardware level.

Other devices cannot transcode at the hardware level, and this is where the codecs used by mpv-android, mxplayer ..etc come into play (they activate the transcoding at the software level)

When testing with both devices, using mpv-android , mxplayer, exoplayer ..etc, they worked perfectly so far.

Everything seems to indicate that the build of mpv and explayer used in findroid, have some problem in detecting the transcoding of devices, which only support at the software level

**Comment by AnonymousWebHacker** [comment]
### Update
I tried a build made by a user of jellyfin adroid + mpv , and it works great. It would be necessary to check what is different about that mpv to the findroid

https://github.com/NIK679/jellyfin-android/releases

**Comment by jarnedemeulemeester** [comment]
Okay so I have the same problem on my device (PIxel 6). Using mpv, if I force software decoding, all 10-bit files (only tested H.264 and HEVC) are very laggy. 

The build of mpv you used in the jellyfin-android+mpv build is using an older build of libmpv. This older version does not have that issue. I only noticed this in newer versions. Findroid, as you may guess, uses a newer version of libmpv.
Now the strange part is that the newest version of mpv-android does not have this issue.
The build of libmpv used in Findroid is almost exactly the same as the one in mpv-android. 

One thing I don't want to do is downgrade to a previous version of libmpv. I would rather fix the issue.

I also plan on making the libmpv library available on GitHub so that other people can also contribute and help with issues. 

So the main issue is:
All 10-bit content fails to play correctly on mpv using software decoding.
Am I correct in saying this?

**Comment by AnonymousWebHacker** [comment]
All 10-bit content fails to play correctly on mpv (findroid build) using software decoding.

**Comment by AnonymousWebHacker** [comment]
@jarnedemeulemeester Findroid are using https://github.com/mpv-android/mpv-android ? 

Jellyfin Test https://github.com/NIK679/jellyfin-android/releases is using this mpv build  https://github.com/CarlosOlivo/jellyfin-android/tree/mpv from CarlosOlivo 

This mpv build , have this changes 
https://github.com/CarlosOlivo/mpv-android/commit/e3defbb569e5d7c47ac617c148a5b641b714233f#diff-51a0b488f963eb0be6c6599bf5df497313877cf5bdff3950807373912ac1cdc9

**Comment by jarnedemeulemeester** [comment]
> @jarnedemeulemeester Findroid are using https://github.com/mpv-android/mpv-android ?

No, Findroid is using a slightly modified version of https://github.com/CarlosOlivo/mpv-android/tree/libmpv

**Comment by AnonymousWebHacker** [comment]
> > @jarnedemeulemeester Findroid are using https://github.com/mpv-android/mpv-android ?
> 
> No, Findroid is using a slightly modified version of https://github.com/CarlosOlivo/mpv-android/tree/libmpv

There are chances to test a beta with  https://github.com/mpv-android/mpv-android ?
It is more updated

**Comment by jarnedemeulemeester** [comment]
Well, https://github.com/CarlosOlivo/mpv-android/tree/libmpv is just changes made on https://github.com/mpv-android/mpv-android
I took those changes and applied them myself with updated dependencies.
So the build in Findroid is already more up to date.

But don't worry, I am testing different versions to find out where the problem lies.

**Comment by jarnedemeulemeester** [comment]
After searching around the internet for people with a simular issue I found out that mpv-android also had this exact problem.
The fix is to disable `vd-lavc-dr` https://github.com/mpv-android/mpv-android/commit/ffd1e8f5e0bb40a9014481a41ae9bad48866381e
I will apply the same option to mpv in Findroid.

**Comment by AnonymousWebHacker** [comment]
Looking forward to the new build :)

**Comment by AnonymousWebHacker** [comment]
@jarnedemeulemeester When will there be a new release?

**Comment by jarnedemeulemeester** [comment]
When I'm done implementing user switching. New release should be this month.

**Comment by AnonymousWebHacker** [comment]
Is there any possibility to test a beta or prebuild , to check the mpv changes?

**Comment by AnonymousWebHacker** [comment]
OMG Fixeddd Tnks :)

**Comment by jarnedemeulemeester** [comment]
Maybe in the future. But for now the mpv player is still experimental

**Comment by AnonymousWebHacker** [comment]
@jarnedemeulemeester Exoplayer update https://github.com/google/ExoPlayer/releases/tag/r2.18.2

**Comment by jarnedemeulemeester** [comment]
@AnonymousWebHacker I have already updated ExoPlayer to 2.18.2. It's in the main branch already...

I also have set up a GitHub bot which automatically creates pull requests for dependency updates so no need to ping me :)

**Comment by AnonymousWebHacker** [comment]
@jarnedemeulemeester I am reproducing this error on other devices.

It was fixed for low ranges like Redmi 9A, I go to settings, enable mpv and the transcoding at the software level works perfectly.

However, in slightly higher range devices such as Samsungs, with 4 GB of RAM, and with native support for transcoding at the hardware level, they will not work with exoplayer, nor with mpv.

I will make a more detailed report in the following hours

**Comment by AnonymousWebHacker** [comment]
@jarnedemeulemeester 
Device: `Xiaomi Redmi Note 11 4G` 
RAM: `4 gb RAM`
CPU: `Mediatek Helio G88` 
Android: 11

`Exoplayer`
Supposedly it has hardware-level decoding, it's a good micro, 4 gb of ram, and a high-end cell phone, so to speak. However exoplayer is not able to play HEVC 10Bit

`mpv options`
With the mpv option enabled, it plays, but without video, only the audio is heard

`others mpv options`
I tried changing the Hardware Decoding `no`, `mediacodec` and `mediacodec-copy`  
I also tried changing the `video output` to `gpu-next` and the same results 
(Either it plays without video, or it plays slowly, as if it were a lot of quality for that device.)
