### ISSUE TITLE
Firestick support?

### ISSUE THREAD

**Issue by samhanna84** [jarnedemeulemeester/findroid#359]
Is there any chance that there will be support for the firestick?

**Comment by decisoft** [comment]
[](https://github.com/jarnedemeulemeester/findroid/issues/23#issuecomment-1326626861), from #23

**Comment by jarnedemeulemeester** [comment]
The Android TV version will be available on Fire TV devices running Android 8.1 and higher.

Follow #23 for news on the TV version of Findroid.

**Comment by TheCez** [comment]
Hi I bought a Fire TV stick 4K recently in a sale, turns out it is 1st gen and now I can't install Findroid TV version because this firestick supports only Fire OS 6.7. So is there any chance you will lower the API level to support older yet capable FireTV sticks?

**Comment by dkadavarath** [comment]
> Hi I bought a Fire TV stick 4K recently in a sale, turns out it is 1st gen and now I can't install Findroid TV version because this firestick supports only Fire OS 6.7. So is there any chance you will lower the API level to support older yet capable FireTV sticks?

Stuck in the same pit here. Have been using the first gen device since launch. Can't complain, everything still works on there like day 1, but finally met the first hurdle on the way. I know all blame is to Amazon for abandoning a perfectly fine device, but if it's possible at all to reduce the API requirements, looking forward to it. Love your work so far, and this app was the final piece of the puzzle that made me shutdown Plex for good. If nothing works out, will just buy a couple of new devices and finally get out of Amazon's grip.
