### ISSUE TITLE
[Help] Installing findroid on android TV (Sony Bravia) makes the app show up in system apps

### ISSUE THREAD

**Issue by breaking-loss** [jarnedemeulemeester/findroid#368]
I installed findroid from izzyondroid through the downloaded app , but when I tried to add it to the starting menu it was mussing . On checking the apps setting page I found the app listed under system apps instead of user apps . When it was opened through the setting it worked perfectly fine but it would be very convenient if it was listed under the user apps as it can be added to starting apps .

Findroid universal package from izzyondroid was installed

**Comment by Yash-Garg** [comment]
@breaking-loss since the app doesn't have a `LEANBACK_LAUNCHER` category, hence it doesn't show directly in apps.

I have made some changes for my personal use on TV at https://github.com/jarnedemeulemeester/findroid/commit/575ff6. If you want you can download the debug APK from [the CI here](https://github.com/Yash-Garg/findroid/actions/runs/4973808150).

**Comment by breaking-loss** [comment]
@Yash-Garg thank you , I will check it today .

**Comment by lvfu** [comment]
Hello phone libre armeabi v7a debug.apk. This version of Google Play can be run on my TV to download the latest version. After logging in, the homepage crashes

你好 phone-libre-armeabi-v7a-debug.apk 这个版本我电视上可以运行  google play 下载的最新版进人应用 登陆完毕进入首页会出现崩溃

**Comment by jarnedemeulemeester** [comment]
A separate TV version is in the works. The phone version of the app is not meant to be used on TV.

See #23 for updates on Android TV.
