### ISSUE TITLE
Not able to download to external USB device

### ISSUE THREAD

**Issue by Skyblueborb** [jarnedemeulemeester/findroid#385]
**Describe the bug**
When trying to download any TV/Show, it asks whether to download to Internal storage or external, but i have 2 external devices and it chooses my SD card, before my USB.

**To Reproduce**
1. Go to any movie/tv show episode
2. Click on the download icon
3. Only 2 devices are shown

**Expected behavior**
See a list of 3 items, internal, external SD, external USB

**Screenshots**
![image](https://github.com/jarnedemeulemeester/findroid/assets/73354158/3fe5312d-775c-4b9d-b28e-03fb384a9760)
![image](https://github.com/jarnedemeulemeester/findroid/assets/73354158/a3c79f6a-fc32-416a-a4d0-11c12d5b60e2)

**Device info (please complete the following information):**
 - Device: Xiaomi Mi A3
 - Android version: 13
 - App version: 0.11.1
 - Jellyfin version: 10.9.0

**Additional context**
The sdcard is formatted as fat32 (4gb in size), usb is exfat (64gb in size)

**Comment by jarnedemeulemeester** [comment]
Only SD cards are supported as external storage location in Findroid.
This is because of how the Android OS sees the SD-card and USB storage.

We use this method to get the external storage directories:
https://developer.android.com/reference/kotlin/android/content/Context#getexternalfilesdirs

> Shared storage devices returned here are considered a stable part of the device, including physical media slots under a protective cover. The returned paths do not include transient devices, such as USB flash drives connected to handheld devices. 

SD-cards are truly "external storage" while USB storage devices are not.

Right now I have no plans to add support for external USB storage as this would require a lot of code changes and extra runtime permissions. I blame Android for this.

**Comment by Panda260** [comment]
is there a plan to support a usb stick in the future?
