### ISSUE TITLE
能否增加播放画面的比例为拉伸或者填充，目前为裁剪

### ISSUE THREAD

**Issue by Joker-lm** [jarnedemeulemeester/findroid#399]
首先感谢作者的付出，然后有个请求，能否增加播放画面的比例为拉伸或者填充，更好的利用手机屏幕，目前放大后的播放画面为裁剪，有些内置字幕就看不到了，谢谢作者。

**Comment by jarnedemeulemeester** [comment]
Sorry, fill / stretch is not something I will be adding because it distorts the video's aspect ratio and (in my opinion) ruins the viewing experience. The fact that some subtitles are no longer visible when cropped is dependent on the type of subtitles and how they are positioned, there is not much I can do about that.

**Comment by Joker-lm** [comment]
好的，谢谢作者！感谢
