### ISSUE TITLE
Offline mode doesn't download external subtitles

### ISSUE THREAD

**Issue by Chemrat** [jarnedemeulemeester/findroid#421]
**Describe the bug**
Offline mode doesn't seem to download external subtitles, rendering it somewhat useless for videos without built-in ones

**To Reproduce**
1. Get a video that has subtitles as an external file
2. Download it for offline playback
3. Start playback, tap on CC button, it does nothing if mpv player is not enabled, with mpv player it shows empty list; no subtitles are displayed during playback either way
4. After one deletes the offline download for the movie, playback now works with subtitles again

**Expected behavior**
Offline mode should also contain subtitles for the movie

**Device info (please complete the following information):**
 - Device: Samsung SM-P615
 - Android version: 13
 - App version: 0.10.1
 - Jellyfin version: 10.8.10

**Comment by Natanel-Shitrit** [comment]
After reviewing the code for a different issue (#430), I found the source of your problem.
It's possible to download videos on mobile data as long as it's allowed it in the 'Downloads' preferences.

The problem with external media can be found in the following code:
https://github.com/jarnedemeulemeester/findroid/blob/43bd2621d12d27bb4d7ad2888bb60d898a05a2ca/core/src/main/java/dev/jdtech/jellyfin/utils/DownloaderImpl.kt#L213-L231

You can see that when queuing items to download - it's marked for download on WIFI only!
https://github.com/jarnedemeulemeester/findroid/blob/43bd2621d12d27bb4d7ad2888bb60d898a05a2ca/core/src/main/java/dev/jdtech/jellyfin/utils/DownloaderImpl.kt#L225

This causes the external media downloads to be pending until a WIFI is connected.

It can be fixed by using the 'Downloads' preferences in external media downloads as well. (or create a different setting for it)
