### ISSUE TITLE
Can’t install from Amazon to FireTV due to geographical restrictions

### ISSUE THREAD

**Issue by lukasl96** [jarnedemeulemeester/findroid#454]
**Describe the bug**
No Bug in the Application itself, it’s just not available in Germany via Amazon Appstore.

**To Reproduce**
1. Go to the Amazon Download Link

**Expected behavior**
Able to install the Application 

**Screenshots**
![image](https://github.com/jarnedemeulemeester/findroid/assets/57773842/64b48108-5b4c-4aad-a340-ba98c50bcded)

**Device info (please complete the following information):**
 - Device: iPhone (in order to install on FireTV)
 
**Additional context**
-

**Comment by jarnedemeulemeester** [comment]
Findroid is not available on FireTV yet. It's only available on FireOS tablets.
The TV version is still being build and when finished will be released to Android TVs running Android 9+ (including Fire TV).

I don't know why it says "due to geographical restrictions" because I put no restrictions on it. It should be available everywhere.
