### ISSUE TITLE
Adding support for Fire TV OS 6 too

### ISSUE THREAD

**Issue by TheCez** [jarnedemeulemeester/findroid#650]
Is it possible for you to lower the API level for TV version so that some older Fire TV sticks can also get support for this app? I recently bought the 4k version and apparently the plan for Fire TV OS 7 is scrapped for 1st gen because they released a new gen recently.

This devices are still very capable for streaming  :)

**Comment by jarnedemeulemeester** [comment]
Sorry I will not be lowering the minimum API level to 25 (Fire TV OS 6 / Android 7.1). Lowering the API level requires a lot of extra checks / workarounds to make sure everything still works correctly. And as a solo developer I just don't have the time for that.

Blame Amazon for not updating their devices.

You can probably still use the official Jellyfin Android TV app since that supports Android 5+ :slightly_smiling_face:
