### ISSUE TITLE
Watch progress/watched status is not synched from FinDroid to web JellyFin

### ISSUE THREAD

**Issue by JKHSDTV** [jarnedemeulemeester/findroid#809]
**Describe the bug**
Watch progress/watched status is not synched from FinDroid to web JellyFin

**To Reproduce**
1. Watch something on FinDroid
2. Open the web interface of JellyFin (or any other JF client)
3. Notice how the watch progress/watched status on episodes is not synced

**Expected behavior**
I expect the status to by synced

**Device info (please complete the following information):**
 - Device: Galaxy Tablet S8
 - Android version: 14
 - App version: 0.15.0
 - Jellyfin version: 10.9.9

**Comment by Grummm** [comment]
I think you may want to take a look at your setup cause this works fine for me, just checked.
It can of course be an edge case, but the fact that it works for me tells me it's probably something being funky on your end.

Did you exit the player properly? In my experience the watch progress on the official desktop player can get kinda inaccurate when not closing the player properly. (Closing the entire window instead of pressing the arrow in the top left) Maybe that's also the case with findroid.
Could sound a bit stupid but if you were watching downloaded media it could be the device wasn't connected to the internet.
And lastly you could just try reloading the web UI. Maybe it was just being slow.

If none of this works and it's actually a bug in findroid I think it's going to take a while until it's fixed cause I haven't seen anyone else  mention something like this and that probably means it's something very specific to your device/server that's going to be hard to find and iron out. (Although this isn't my project so who knows)

**Comment by JKHSDTV** [comment]
Knowing it's supposed to work like this certainly helps; I'll experiment some more. I reloaded the web client multiple times, and I both watched and exited regularly, but also used the 'mark as watched' feature, and that didn't carry over either.

**Comment by jarnedemeulemeester** [comment]
Also works just fine for me.
Are you sure you are running Jellyfin 10.9? There were some changes in the API related to playback syncing but Findroid 0.15.0 should be compatible with Jellyfin 10.9. 
If you we're running 10.8 that would explain the issues.
