### ISSUE TITLE
Support for AVIF images

### ISSUE THREAD

**Issue by enter-a-random-username** [jarnedemeulemeester/findroid#819]
**Is your feature request related to a problem? Please describe.**
At the moment it needs Android 12+ for AVIF support and players have no problem with AV1 software support. 

**Describe the solution you'd like**
Add a software decoder like jellyfin app supports. To be clear the backend aka server thumbnailer has no avif support (yet), but using AVIF works without a problem and will return original image.

**Additional context**
AVIF is has major browser support and right click "Save as" can be AVIF in jpg or png file extension or avif. Similar with webp before. CDNs deliver images based on browser capability's.

**Comment by jarnedemeulemeester** [comment]
We rely on https://github.com/coil-kt/coil for displaying all images. Coil has support for AVIF in Android 12+.
The Jellyfin app uses webviews which are chromium based and include a AVIF decoder.

I think already supporting AVIF on Android 12 and newer is plenty. And besides, this decoder would need to be added to coil instead of directly in Findroid.
