### ISSUE TITLE
Feature: Download progress indicator

### ISSUE THREAD

**Issue by OctoNezd** [jarnedemeulemeester/findroid#87]
Right now there is no way to track downloads progress and impossible to check if download got stuck or is even happening

**Comment by fmchris10** [comment]
This would be a good addition to the download function.

I've tried several times to test the download function and, I have never been able to complete a download. I left it for almost an hour, the file is about 300mb and I have managed to watch several episodes after giving up within the time it did nothing.

**Comment by Jcuhfehl** [comment]
Actually, there is supposed to be an indicator in the notifications menu from the system download manager, and it seems the reason you're not getting a notification is because the download is not starting at all, as reported in #210. Unfortunately, I have no idea why they fail to start, maybe you could try manually giving the app the files and media permission but I'm basically just guessing at this point.

**Comment by OctoNezd** [comment]
Sometimes downloads start and you get a notification - but the issue is that I can go out of wifi/mobile data range and download fails silently, with no indication in notifications or in the app.

**Comment by Jcuhfehl** [comment]
Oh that's indeed a different issue with the system download manager which I also have, but don't know how to solve except for writing our own download manager (which is a plan for the long term). For now you should know that if the download doesn't show up in the notifications it probably failed.
